
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author welcome
 */
public class LoanAssistantProject extends javax.swing.JFrame {
    private boolean Computebutton;
    private Object ComputePayment; 
    double loan;
    double interest;
    double month;
    double payment;
    double MonthlyPayment;
    
    public LoanAssistantProject() {
        initComponents();
        xMonthButton.doClick();
        AnalysisButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BalanceField = new javax.swing.JTextField();
        InterestField = new javax.swing.JTextField();
        PaymentField = new javax.swing.JTextField();
        MonthlyField = new javax.swing.JTextField();
        ComputeButton = new javax.swing.JButton();
        AnalysisButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        xPaymentButton = new javax.swing.JButton();
        xMonthButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Loan Balance");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Interest Rate:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Number Of Payement:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Monthly Payment:");

        BalanceField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BalanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceFieldActionPerformed(evt);
            }
        });

        InterestField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        InterestField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterestFieldActionPerformed(evt);
            }
        });

        PaymentField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        MonthlyField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MonthlyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthlyFieldActionPerformed(evt);
            }
        });

        ComputeButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ComputeButton.setText("Compute Monthly Payment");
        ComputeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputeButtonActionPerformed(evt);
            }
        });

        AnalysisButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AnalysisButton.setText("New Loan Analysis");
        AnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisButtonActionPerformed(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Loan Analysis");

        ExitButton.setText("EXIT");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        xPaymentButton.setText("X");
        xPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPaymentButtonActionPerformed(evt);
            }
        });

        xMonthButton.setText("X");
        xMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xMonthButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(MonthlyField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PaymentField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InterestField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BalanceField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xMonthButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(xPaymentButton))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(114, 114, 114))))
            .addGroup(layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(AnalysisButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(ComputeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InterestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xPaymentButton))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(MonthlyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xMonthButton))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComputeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton))
                .addGap(18, 18, 18)
                .addComponent(AnalysisButton)
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InterestFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterestFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InterestFieldActionPerformed

    private void AnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisButtonActionPerformed
        
        BalanceField.setText("");
        InterestField.setText("");
        PaymentField.setText("");
        TextArea.setText("");
        AnalysisButton.setEnabled(false);
        ComputeButton.setEnabled(true);
        
        
    }//GEN-LAST:event_AnalysisButtonActionPerformed

    private void xPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPaymentButtonActionPerformed
       Computebutton = true;
       xPaymentButton.setVisible(false);
       xMonthButton.setVisible(true);
       MonthlyField.setEditable(true);
       MonthlyField.setBackground(Color.white);
       MonthlyField.setFocusable(true);
       PaymentField.setEditable(false);
       PaymentField.setBackground(Color.yellow);
       PaymentField.setFocusable(false);
       BalanceField.requestFocus();
       
       
       
       
    }//GEN-LAST:event_xPaymentButtonActionPerformed

    private void MonthlyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthlyFieldActionPerformed
        
    }//GEN-LAST:event_MonthlyFieldActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void xMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xMonthButtonActionPerformed
        Computebutton = false;
       xPaymentButton.setVisible(true);
       xMonthButton.setVisible(false);
       MonthlyField.setEditable(false);
       MonthlyField.setBackground(Color.red);
       MonthlyField.setFocusable(false);
       PaymentField.setEditable(true);
       PaymentField.setBackground(Color.white);
       PaymentField.setFocusable(true);
       BalanceField.requestFocus();
       ComputeButton.setVisible(true);
    }//GEN-LAST:event_xMonthButtonActionPerformed

    private void ComputeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputeButtonActionPerformed
        String iMonthPayment = String.format(MonthlyField.getText());
        
        if(BalanceField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You must enter amoun of Balance",
                    "Loan System",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            loan = Double.parseDouble(BalanceField.getText());
            String Balance = String.format(BalanceField.getText());
        }
        if(InterestField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You must enter amoun of Interest Rate",
                    "Loan System",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            interest = Double.parseDouble(InterestField.getText());
            String iInterest = String.format(InterestField.getText());
        }
           
        if(PaymentField.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You must enter amoun of Number of Payment",
                    "Loan System",JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            month = Double.parseDouble(PaymentField.getText());
            String iMonth = String.format(PaymentField.getText());
        }
        payment = loan + ((loan * interest)/100);
        
        MonthlyPayment = payment / month;
        String PayMonth = String.format("%.2f",MonthlyPayment);
        MonthlyField.setText(PayMonth);
        TextArea.append("\t\n Loan Assistan Project:\n\n"+
                                " Amoun of Loan:\t $"+ loan +
                                "\n Number of Payment:\t $"+ interest+
                                "\nMonthly Payment:\t $" + month+ 
                                "\nPayment Per Month:\t $" +MonthlyPayment+ 
                                "\nTotal Loan Payment:\t $" +payment+ 
                                "\n\nTHANKS FOR USING NK LOAN ASSISTANT SYSTEM");
        AnalysisButton.setEnabled(true);
       ComputeButton.setEnabled(false);
    }//GEN-LAST:event_ComputeButtonActionPerformed

    private void BalanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAssistantProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAssistantProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAssistantProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAssistantProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanAssistantProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalysisButton;
    private javax.swing.JTextField BalanceField;
    private javax.swing.JButton ComputeButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField InterestField;
    private javax.swing.JTextField MonthlyField;
    private javax.swing.JTextField PaymentField;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton xMonthButton;
    private javax.swing.JButton xPaymentButton;
    // End of variables declaration//GEN-END:variables
}
